# Generated by Django 3.0.8 on 2020-09-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200829_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
