# Generated by Django 3.0.8 on 2020-09-07 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200907_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='listid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.Listings'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
